<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FeeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => 1,
                'fee_type_id' => 1,
                'fee_description' => 'application fee, full and one-off',
                'amount' => 2250,
                'is_one_off' => 1,
                'application_level_id' => 9,
                'institution_id' => 1,
                'programme_id' => '0',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => '0',
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 2,
                'fee_type_id' => 2,
                'fee_description' => 'result check fee, full and one-off',
                'amount' => 1250,
                'is_one_off' => 1,
                'application_level_id' => 9,
                'institution_id' => 1,
                'programme_id' => '0',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => '0',
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 3,
                'fee_type_id' => 3,
                'fee_description' => 'acceptance fee, full and one-off',
                'amount' => 15250,
                'is_one_off' => 1,
                'application_level_id' => 9,
                'institution_id' => 1,
                'programme_id' => '0',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => '0',
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 4,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 100, full and not one-off',
                'amount' => 77300,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 1,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 5,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 100, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 1,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 6,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 100, final-payment and not one-off',
                'amount' => 33550,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 1,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 7,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 200, full and not one-off',
                'amount' => 66800 ,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 2,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 8,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 200, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 2,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 9,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 200, final-payment and not one-off',
                'amount' => 27050,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 2,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 10,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 300, full and not one-off',
                'amount' => 66800 ,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 3,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 11,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 300, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 3,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 12,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 300, final-payment and not one-off',
                'amount' => 27050,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 3,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 13,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 400, full and not one-off',
                'amount' => 66800 ,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 4,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 14,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 400, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 4,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 15,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 400, final-payment and not one-off',
                'amount' => 27050,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 4,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 16,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 500, full and not one-off',
                'amount' => 66800 ,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 5,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 17,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 500, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 5,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 18,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 500, final-payment and not one-off',
                'amount' => 27050,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 5,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 19,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 600, full and not one-off',
                'amount' => 66800 ,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => 1,
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 6,
                'payment_type_id' => 1,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 20,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 600, first-payment and not one-off',
                'amount' => 40250,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 6,
                'payment_type_id' => 2,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ],
            [
                'id' => 21,
                'fee_type_id' => 4,
                'fee_description' => 'school fees for level 600, final-payment and not one-off',
                'amount' => 27050,
                'is_one_off' => 0,
                'application_level_id' => 10,
                'institution_id' => '0',
                'programme_id' => '1',
                'faculty_id' => '0',
                'department_id' => '0',
                'field_id' => '0',
                'level_id' => 6,
                'payment_type_id' => 3,
                'j_regno' => '0',
                'regno' => '0',
                'created_by' => 2,
                'updated_by' => 2,
                'active' => 1
            ]
        ];
        DB::table('sch_fee')->insert($data);
    }
}
